near/near-discovery-components

src/Comments/Comment.jsx, src/ComponentDetailsPage.jsx, src/ComponentSummary.jsx, src/NestedDiscussions/Preview.jsx, src/Onboarding/ComponentCard.jsx, src/Onboarding/ComponentCollection.jsx, src/Posts/Post.jsx, src/ProfilePage/Sidebar.jsx
Waiting to merge this once the `near.org` domain has been set up.
=> Switching from alpha.near.org to near.org

src/ComponentDetailsPage.jsx, src/NestedDiscussions.jsx
We now notify the owner of a widget when somebody comments on their widget's discussion.
=> Notify Owner

src/Search/Markdown.jsx, src/Search/PostCard.jsx, src/Search/TypeAheadDropdown.jsx
Fixed 
-App tab not filtering out other components 
- UI issues with posts 
- markdown formatting
=> Fixed Dropdown Bugs

src/TosCheck.jsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1148
=> Check ToS only for authenticated users

src/Search/Markdown.jsx, src/Search/PostCard.jsx, src/Search/TypeAheadDropdown.jsx
Highlighting word searched in comments 
fixed font color issue in posts set to #606D7A
=> fixed formatting on markdown

src/Search/ComponentCard.jsx, src/Search/DropdownAccountCard.jsx, src/Search/IndexPage.jsx, src/Search/PostCard.jsx, src/Search/TypeAheadDropdown.jsx
=> fix: typeahead alignment and arrows

src/ProfilePage/Sidebar.jsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1165
=> Fix long content overflow on large device

src/Posts/Edit.jsx, src/Posts/Menu.jsx, src/Posts/Post.jsx
This PR adds the ability to edit posts (and only posts, no comments), the idea is that we can discuss if we like this approach.
=> Edit Posts

vm.d.ts
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1127
Generated types for:
=> Generate type declarations

src/ComponentDetailsPage.jsx, src/WaitList.jsx
- Ports over `WaitList` component
- Fixes `ComponentDetailsPage` since we had forgot to port over the wait list component earlier.
- Made the `WaitList` component customizable via props.
=> Wait List Fixes

src/Search/TypeAheadDropdown.jsx
The typeahead didn't have the correct query id when a user goes to click a search hit. This will fix that. Clicking posts also didn't have any analytics tracking so added that too.
=> fix: typeahead analytics not having queryID

src/FeaturedComponents.jsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1236
=> Add `Horizon` widget to featured components

src/ActivityPage.jsx, src/ComponentDetailsPage.jsx, src/ComponentsPage.jsx, src/Feed/Post.jsx, src/NestedDiscussions.jsx, src/NestedDiscussions/Compose.jsx, src/NestedDiscussions/Feed.jsx, src/Notification.jsx, src/PeoplePage.jsx, src/Posts.jsx, src/Posts/Compose.jsx, src/Posts/Edit.jsx, src/Posts/Feed.jsx, src/ProfilePage.jsx, src/ProfilePage/Sidebar.jsx, src/Search/Facets.jsx, src/Search/TypeAheadDropdown.jsx
It's not so clear which element should change depending on mobile or desktop. I tested it locally and it seems to be OK but still need some eyes on it.
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1318
Relates to: https://github.com/near/near-discovery/pull/280
=> Change desktop minimal width

.github/workflows/promote-develop-to-main.yml
add a workflow which creates a PR promoting deploy to main every week
=> automate the creation of prod deployment PRs

src/DIG/Accordion.jsx, src/DIG/Accordion.metadata.json
Example usage:
```jsx
return (
<Widget
src="near/widget/DIG.Accordion"
props={{
type: "multiple",
defaultValue: ["1"],
items: [
{
value: "1",
header: "Header 1",
content: (
<>
<p>My JSX context 1.</p>
<p>Here's another paragraph.</p>
</>
),
},
{
value: "2",
header: "Header 2",
content: (
<>
<p>My JSX context 2.</p>
<p>Here's another paragraph.</p>
</>
),
},
],
}}
/>
);
```
=> Created `DIG.Accordion` Component

src/DIG/Badge.jsx, src/DIG/Badge.metadata.json
Example:
```jsx
return (
<Widget
src="near/widget/DIG.Badge"
props={{
label: "Hello",
iconLeft: "ph-bold ph-pizza",
variant: "warning",
}}
/>
);
```
=> Implemented DIG.Badge

src/DIG/Checkbox.jsx, src/DIG/Checkbox.metadata.json
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1346
=> Implement DIG.Checkbox

src/DIG/Chip.jsx, src/DIG/Chip.metadata.json
Example:
```jsx
return (
<Widget
src="near/widget/DIG.Chip"
props={{
label: "My Chip",
iconLeft: "ph-bold ph-pizza",
onClick: () => console.log("click"),
}}
/>
);
```
=> Implemented DIG.Chip

src/DIG/Input.jsx, src/DIG/Input.metadata.json
Example:
```jsx
State.init({
myValue: "",
});
return (
<Widget
src="near/widget/DIG.Input"
props={{
assistiveText: "My assistive text",
label: "My Label",
iconLeft: "ph-bold ph-pizza",
placeholder: "Placeholder...",
onInput: (e) => State.update({ myValue: e.target.value }),
value: state.myValue,
}}
/>
);
```
=> Implement basic DIG.Input

src/AccountProfileInline.jsx, src/AccountProfileOverlay.jsx, src/NestedDiscussions/Preview.jsx, src/ProfilePage/Sidebar.jsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1349
This is how `FlagButton` looks like on profile page:
and on tooltip:
From now we using the same `AccountProfileOverlay` component everywhere.
=> DEC-1349: Add the ability to complain about user profiles

src/DIG/Input.jsx, src/DIG/InputTextarea.jsx, src/DIG/InputTextarea.metadata.json
Example
```jsx
State.init({
myValue: "",
});
return (
<Widget
src="near/widget/DIG.InputTextarea"
props={{
assistiveText: "My assistive text",
label: "My Label",
placeholder: "Placeholder...",
onInput: (e) => State.update({ myValue: e.target.value }),
value: state.myValue,
}}
/>
);
```
=> Implemented DIG.InputTextarea

src/ActivityPage.jsx, src/Comments/Comment.jsx, src/Feed.jsx, src/LikeButton.jsx, src/PostPage.jsx, src/Posts.jsx, src/Posts/Feed.jsx, src/Posts/Post.jsx
near.org feed powered with QueryAPI
=> DEC-1370 feat: port queryapi feed -> near-discovery-components

src/AccountProfileOverlay.jsx, src/Comments/Comment.jsx, src/NestedDiscussions/Preview.jsx, src/Posts/Post.jsx, src/ProfilePage/Sidebar.jsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1350
=> DEC-1350: Display a Toast message on each flagged item 

src/ComponentCard.jsx
=> lock TimeAgo dependency to previous version

src/Posts.jsx, src/Select.jsx
Loom video to show the feature: https://www.loom.com/share/ba0eddca96ad4c17bbd263411df45074
=> feat: implement recent comments sort option

src/ProfilePage.jsx
=> Fix posts list on profile page

replacements.dev.json, replacements.mainnet.json, replacements.testnet.json, src/AccountProfile.jsx, src/Comments/Comment.jsx, src/ComponentCard.jsx, src/ComponentDetailsPage.jsx, src/Flagged/Feed.jsx, src/LatestFollowActivity.jsx, src/LatestNews.jsx, src/NestedDiscussions/Preview.jsx, src/Notification.jsx, src/Onboarding/ComponentCard.jsx, src/Posts/Post.jsx, src/Search/AccountProfile.jsx, src/v1/Posts/Post.jsx
Version locking the component for mainnet broke it on testnet. The version lock is now driven by replacements
=> Fix TimeAgo component on testnet

src/DIG/Dialog.jsx
This fix allows to pass onClick actions properly
=> Fix DIG.Dialog action click

src/Comments/Comment.jsx, src/Feed/Post.jsx, src/Posts/Post.jsx, src/v1/LikeButton.jsx, src/v1/Posts/Post.jsx
fixes like button near.org feed.
=> fixes like button

src/AccountProfileOverlay.jsx, src/Comments/Comment.jsx, src/DIG/Dialog.jsx, src/FlagButton.jsx, src/NestedDiscussions/Compose.jsx, src/NestedDiscussions/Preview.jsx, src/Posts/Compose.jsx, src/Posts/Edit.jsx, src/Posts/Post.jsx, src/v1/Posts/Post.jsx
=> Fix Like Button + Post Preview

src/AccountProfileOverlay.jsx, src/Comments/Comment.jsx, src/NestedDiscussions/Preview.jsx, src/Posts/Post.jsx, src/ProfilePage/Sidebar.jsx
In favour of `DIG.Toast` report message let's remove the old message once somebody flags something
=> Remove old report message

src/v1/LikeButton.jsx
Add actual v1 likeButton with updated styles.
=> fix: update to v1 likeButton

src/DIG/Dialog.jsx
=> Fix styling options of `DIG.Dialog`

src/NearOrg/Notifications/NotificationAlert.jsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1430
=> Add `NotificationAlert`

src/Posts.jsx
Feed side of UI implemented in https://github.com/near/near-discovery-components/pull/159
See discussion https://github.com/near/near-discovery/discussions/386
=> feat: Filter out accounts and posts that have been self moderated

src/TosCheck.jsx
Relates to: https://github.com/near/near-discovery/pull/551
=> Record ToC state for notifications

src/NearOrg/Notifications/NotificationButton.jsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1431
Example of usage:
```jsx
<Widget
src="discom.testnet/widget/NearOrg.Notifications.NotificationButton"
props={{
previewItems: <NotificationsList />,
showMoreButton: <ShowMore />,
notificationFeedSrc: components.nearOrg.notifications.page;
}}
/>
```
=> Add notification preview

src/ProfilePage.jsx
This PR updates ProfilePage to redirect to an accountId's custom profile page if it exists.
=> encourage the creation of custom profile components

src/TosCheck.jsx
=> Remove non-callable function

src/AccountProfileOverlay.jsx, src/NearOrg/Notifications/Notification.jsx, src/NearOrg/Notifications/NotificationButton.jsx
=> Fix`NotificationButton` issues

src/AppLibrary/IndexPage.metadata.json
Closes: https://github.com/near/near-discovery-components/issues/355
=> Adding metadata and description for App Library page

src/NearOrg/Notifications/NotificationButton.jsx
Closes: [#576](https://github.com/near/near-discovery/issues/576)
=> Fix new notifications count

src/NearOrg/Notifications/NotificationButton.jsx
Potentially closes [#655](https://github.com/near/near-discovery/issues/655)
=> Fix new notification counter

src/Posts.jsx, src/Posts/Feed.jsx
Closes [#323](https://github.com/near/near-discovery-components/issues/325)
=> Fix `all` and `following` toggles on ActivityPage

src/NearOrg/CookiePolicy.jsx
https://www.loom.com/share/03784d81a11a452bba28030c9cf881a0
=> chore: new component to display our cookie policy

src/NearOrg/Notifications/Banner.jsx, src/NearOrg/Notifications/NotificationAlert.jsx, src/NearOrg/Notifications/Notifications.jsx, src/NearOrg/Notifications/Settings.jsx, src/NearOrg/Notifications/SettingsHeader.jsx
Relates to [#667](https://github.com/near/near-discovery/issues/667)
=> Add note about minimal required iOS version for notifications

indexers/verifications/verifications.js, indexers/verifications/verifications.sql
This is a reference copy of the moderation indexer. The running code at https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=dataplatform.near/verifications&view=editor-window is the source of truth.
=> Reference copy of the verifications indexer

indexers/social_feed/social_feed.js, indexers/social_feed/social_feed.sql, indexers/verifications/verifications.js, indexers/verifications/verifications.sql, replacements.testnet.json
This is a reference copy of the moderation indexer. The running code at https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=dataplatform.near/social_feed&view=editor-window is the source of truth.
=> Reference copy of the social_feed indexer

src/AccountProfileOverlay.jsx
Fixes: https://github.com/near/near-discovery-components/issues/402
Hey @gabehamilton, I did some investigating after reviewing your PR and realized the fix was going to be a bit more complex. Hope you don't mind I went ahead and implemented a fix. :)
Please feel free to test and let me know if you have questions.
=> Fix mention whitespace bug

src/NearOrg/BosCtaSection.jsx, src/NearOrg/Card.jsx, src/NearOrg/Ecosystem/CommunityPage.jsx, src/NearOrg/Ecosystem/GetFundingPage.jsx, src/NearOrg/Ecosystem/OverviewPage.jsx, src/NearOrg/Ecosystem/WorkAndEarnPage.jsx, src/NearOrg/EcosystemPage.jsx, src/NearOrg/Footer.jsx, src/NearOrg/HomePage.jsx, src/NearOrg/LearnPage.jsx
Related: https://github.com/near/near-discovery/issues/688
Related: https://github.com/near/near-discovery-components/issues/361
Related: https://github.com/near/near-discovery-components/issues/362
This ticket partially implements the tickets above. I'll be publishing another PR on the gateway soon to fully complete the tickets (I need to update our gateway to actually use the new home, learn, and ecosystem page BOS components).
=> New learn and ecosystem pages + QA fixes

indexers/README.md, indexers/moderation/moderation.js, indexers/moderation/moderation.sql, indexers/social_feed/social_feed.js, indexers/social_feed/social_feed.sql, indexers/verifications/verifications.js, indexers/verifications/verifications.sql, src/Moderation/ModerateAccounts.jsx, src/Moderation/ModerateComments.jsx, src/Moderation/ModeratePosts.jsx, src/Posts.jsx, src/Posts/Menu.jsx, src/Posts/Post.jsx
* Use the moderated posts view for the Feed. Note that QueryApi is currently only running against mainnet.
* Use block height as Int in moderation pages, uncomment moderation account filters that were commented out for testing.
=> Use new moderated_posts table for Post feeds.

src/NearOrg/Notifications/CommentContent.jsx, src/NearOrg/Notifications/CommentPost.jsx, src/NearOrg/Notifications/Notification.jsx
closes https://github.com/near/near-discovery/issues/699
This is a quick fix that leaves room for improvement on the display on the newly added CommentContent.jsx - tracking @ https://github.com/near/near-discovery-components/issues/407
=> fix invalid notification links for mentions and post replies

src/AppLibrary/Search.jsx
Closes: https://github.com/near/near-discovery-components/issues/389
=> Updated App Library Search

src/NearOrg/Notifications/Notification.jsx, src/Search/FullPage/AccountProfileCard.jsx, src/Search/FullPage/ComponentCard.jsx, src/Search/FullPage/PostCard.jsx
=> Fix timeago on testnet

src/Recommender/Engagement/ProfileInfoTracked.jsx
This fixes a ui bug, stacking the paragraph tags vertically as intended.
=> fix(): broken scss in styled component

CONTRIBUTING.md, README.md
This PR introduces updates of `README.md` and `CONTRIBUTING.md`. Mainly updated information about local development
=> chore: Update `README.md`

src/Comments/Comment.jsx, src/Posts.jsx, src/Posts/Menu.jsx, src/Posts/Post.jsx
* Hide and report menus for Comments
* Apply self-moderation to Comments in Feed.
=> Hide and Report menus for Comments

indexers/moderation/moderation.js, indexers/moderation/moderation.sql
These views power the new moderation interface https://github.com/near/near-discovery-components/pull/439
=> Moderation indexer with unmoderated_reports and needs_moderation views

src/ComponentDetailsPage.jsx, src/ComponentHistory.jsx, src/ComponentSummary.jsx
Issue details can be found here: 
https://github.com/near/data-platform/issues/40
=> Component redesign bug fixes 

.github/release.yml, .github/workflows/prs_must_have_labels.yml
Adds a config file for auto-generated release notes based on tags added to PRs
Use one of these tags on your PRs to categorize in the change log. PRs without tags, or with tags that do not match this list, will be added as general enhancements.
bug
feature
breaking-change
dependency
enhancement
=> support auto-generated release notes

src/AppLibrary/Nearcon/IndexPage.jsx
revisisions according to https://near.org/tiffany.near/widget/Untitled-0
=> revise copy - nearcon app quest

src/NearOrg/Notifications/Notification.jsx
Fixed notification issue with DevHub.
=> Fixed notification style for DevHub post

src/AppLibrary/IndexPage.jsx
Updated fetch function for AppStore
=> feat(AppLibrary.IndexPage) Update fetch

src/NearOrg/Notifications/NotificationAlert.jsx
This PR fixes alignment for this buttons:
=> Fix alignment of action buttons for NotificationAlert

ngrok.yml, src/AppLibrary/Nearcon/Charts/TopUpvotedApps.jsx, src/AppLibrary/Nearcon/IndexPage.jsx, src/AppLibrary/Nearcon/IndexPage.metadata.json
Added a uncategorized section to view all components with descriptions
Added Charts to show most upvoted components
=> feature: add leaderboard charts to ncon 

ngrok.yml, src/AppLibrary/Nearcon/Charts/TopUpvotedApps.jsx, src/AppLibrary/Nearcon/IndexPage.jsx
=> chore: delete accidentally checked in file

src/ComponentSummary.jsx
We have to show the `upvote button` on the component details page but there was a bug on this behavior with how we do the checks.
=> fix upvote bug

src/ProfilePage.jsx
Support the latest ProfilePage features for all users on near.org by removing the redirect to a custom ProfilePage component
=> Removes the redirect to a custom ProfilePage component

src/NearOrg/DataAvailabilityPage.jsx
@gagdiez reached out to me letting me know the link to the Data Availability docs had changed.
=> Updating link to DA docs

src/ComponentProfile.jsx
fix caching problem temporarily by redirecting redirecting user to new window which forces a re-render
=> Fix caching issue with component details stats

src/Posts/Post.jsx
This change is on main in commit 64fa5d05f13dba59ed4f44d6544374116119f235, this PR applies it back to develop
=> Apply hotfix: Check type of accounts_liked data before parsing.

src/Moderation/CheckPostModeration.jsx
Closes: [#828](https://github.com/near/near-discovery/issues/828)
=> fix: Rendering post for accounts with no seft moderated data

src/NearOrg/Notifications/CommentContent.jsx, src/NearOrg/Notifications/CommentPost.jsx, src/NearOrg/Notifications/Notification.jsx
=> Align the notification mention UI #533

src/Settings/Identity/Banner.jsx, src/Settings/Identity/Index.jsx, src/Settings/Identity/Verifications/Index.jsx
This PR introduces a couple of changes:
1. The new tooltip about successful connection to idOS.
2. Added a message to the banner to inform users about preferred wallets to use the idOS feature.
3. Made banner visible by default.
4. Added ability to load idOS data on page load
Relates to: #493 #494
=> refactor: Connect to idOS on page load

src/Comments/Comment.jsx, src/Posts/Post.jsx
Fixing comment on comment issue: #359
=> Fix for adding a comments

src/ComponentDetails/Content.jsx, src/ComponentDetails/Sidebar.jsx, src/ComponentDetailsPage.jsx
Closes: [#854](https://github.com/near/near-discovery/issues/854)
=> Refactor `ComponentDetailsPage`

src/Comments/Comment.jsx, src/NearOrg/Notifications/CommentContent.jsx, src/NearOrg/Notifications/CommentPost.jsx, src/Posts/Post.jsx
Fixes https://github.com/near/near-discovery-components/issues/407
- Show content for mentioned notification types
- Show flag icon in comments
- Passed the current data of parentPost in commentPost.jsx
=> Fix: Improve and align notification UI components

src/NearOrg/Footer.jsx
Closes: https://github.com/near/near-discovery-components/issues/553
=> chore: add brandtoolkit to footer

src/ProfilePage.jsx
=> fix: remove explore tab from profile page

src/NearOrg/Notifications/CommentPost.jsx, src/Posts/Post.jsx
This pull request addresses a UI concern related to the positioning of the three dots in the top right corner,
as documented in: https://github.com/near/near-discovery-components/issues/573
- Added `PostWrapper` styled element with a `width: fit-content`
With this change, the `three dots` will appear closer and be aligned with the longest content on the post/comment.
=> Fix: Improved three dots placement in CommentPost component

src/AccountAutocomplete.jsx, src/NearOrg/DataAvailabilityPage.jsx
Closes: https://github.com/near/near-discovery/issues/887
=> 887 data availability comparison chart

replacements.dev.json, replacements.mainnet.json, replacements.testnet.json, src/ComponentHistory.jsx, src/NearOrg/CookiePolicy.jsx
adds bozon.near to REPL configs with testnet equivalent
=> fix code widget on testnet

indexers/accounts/accounts.js, indexers/accounts/accounts.sql
Relates to [#855](https://github.com/near/near-discovery/issues/855)
=> feat: add accounts indexer

src/NearOrg/Notifications/Notification.jsx, src/NearOrg/Notifications/NotificationButton.jsx, src/NearOrg/Notifications/Notifications.jsx, src/NearOrg/Notifications/NotificationsList.jsx, src/NearOrg/Notifications/utils.jsx
This PR includes a bunch of refactoring to improve performance and code readability.
Closes [#779](https://github.com/near/near-discovery/issues/779)
=> Refactor NearOrg/Notifications components

indexers/components/components.js, indexers/components/components.sql
This PR adds metadata to the components indexer.
The SQL schema has been changed due to the old version not properly generating.
=> Metadata in components indexer

src/QueryApi/DataPlatformIndexerStatuses.jsx
=> feat: display QueryApi indexer statuses for a given user

src/NearOrg/DataAvailabilityPage.jsx
=> fix: update data availability partner links

src/AccountProfile.jsx
This Pull Request suggests some changes in the `AccountProfile` file to address the issue https://github.com/near/near-discovery/issues/853.
- Added `returnProfileForUser` function.
- Updated `TimeAgo` widget.
- Added prop `profile: returnProfileForUser(profile)` in AccountProfileOverlay widget.
=> Refactor AccountProfile component

src/NearOrg/Notifications/Notification.jsx
=> fix: exception stack trace on opening the notifications overlay

indexers/components/components.js, indexers/components/components.sql
created a new table "info" to capture forks, stars, and additional metadata for components
=> feat: updated components.sql to capture stars/forks and additional info

src/NearOrg/DataAvailabilityPage.jsx, src/NearOrg/Ecosystem/OverviewPage.jsx, src/NearOrg/HomePage.jsx
=> style: partner logo and copy updates

indexers/feed/relationships.json, src/AccountProfile.jsx, src/ActivityFeeds/PostsFeedControls.jsx, src/Posts/Feed.jsx
Relates to [#855](https://github.com/near/near-discovery/issues/855)
Closes #427
=> feat: use accounts indexer for posts feed

src/NearOrg/DataAvailabilityPage.jsx
Closes [#944](https://github.com/near/near-discovery/issues/944);
Missing links to:
=> chore: update DA page

indexers/agents/agents.js, indexers/agents/agents.sql, src/Entities/AgentFramework/AgentCard.jsx, src/Entities/AgentFramework/AgentChat.jsx, src/Entities/AgentFramework/AgentCreate.jsx, src/Entities/AgentFramework/AgentHeader.jsx, src/Entities/AgentFramework/AgentPage.jsx, src/Entities/Template/EntityList.jsx
Initial components for Agent Framework: page, list (via EntityList), create.
[agent indexer](https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=dataplatform.near%2Fagents&transactionHashes=HhdNUsYKPAcx24KR1QoqYgzXs4dUxVGzwjKvccckqBWP) is live
AgentChat is a copy of an existing prototype and will be reworked in a future PR.
AgentHeader is an experiment.
=> feat: initial agent framework

src/NearOrg/PapersPage.jsx
Relates to https://github.com/near/near-discovery/pull/971
=> feat: create a new component for `papers` page

src/NearOrg/Notifications/Banner.jsx, src/NearOrg/Notifications/Notifications.jsx
Closes [#958](https://github.com/near/near-discovery/issues/958)
=> fix: notification prompt message

src/NearOrg/FoundersPage.jsx, src/NearOrg/PapersPage.jsx
Closes [#975](https://github.com/near/near-discovery/issues/975) [#976](https://github.com/near/near-discovery/issues/976)
[Demo](https://www.loom.com/share/d2db90ba0afa4e4793f29b3887f2924b?sid=02d35900-2f54-4da5-825d-79a76759caf5)
=> feat: create founders page component

src/ComponentSummary.jsx
as per [#995](https://github.com/near/near-discovery/issues/955)
=> feat: simplifying the action buttons on the component details card

src/NearOrg/FoundersPage.jsx
to pick the latest navigation and copy updates
=> develop -> main

src/AI/Agent/AgentChat.jsx, src/DIG/InputSelect.jsx
Support multiple LLM providers: OpenAI, local
Bearer credentials for LLM call.
Settings are stored in local storage
=> feat: agentchat supports multiple providers

src/AI/Agent/AgentCard.jsx, src/AI/Agent/AgentChat.jsx, src/AI/Agent/AgentCreate.jsx, src/AI/Agent/AgentDetails.jsx, src/AI/Agent/AgentSummary.jsx
* an agent may specify a custom chat component
* Additional models in AgentChat
=> Custom chat component

src/AI/Agent/AgentCard.jsx, src/AI/Agent/AgentChat.jsx, src/AI/Agent/AgentCreate.jsx, src/AI/Agent/AgentDetails.jsx, src/AI/Agent/AgentSummary.jsx
* feat: agent custom components
* feat: additional agent models
* feat: json output
=> Custom chat component (#668)

src/NearOrg/FoundersPage.jsx
Closes [#999](https://github.com/near/near-discovery/issues/999)
=> chore: add token checklist file to the founders page

src/NearOrg/FoundersPage.jsx
Closes [#1008](https://github.com/near/near-discovery/issues/1008)
=> chore: update text on founters page

.github/workflows/release_notes.yml, src/NearOrg/FoundersPage.jsx
This is related to https://github.com/near/near-discovery-components/pull/676
=> non-regular promotion develop -> main

src/Events/Card.jsx, src/Events/CardLarge.jsx, src/Events/Index.jsx
Relates to https://github.com/near/near-discovery/pull/1014
TODO items:
=> feat: create an events page component

replacements.dev.json, replacements.mainnet.json, replacements.testnet.json, src/ActivityFeeds/PostsFeedControls.jsx, src/ComponentCard.jsx, src/ComponentDetailsPage.jsx, src/FeaturedComponents.jsx, src/NearOrg/BlockchainPage.jsx, src/NearOrg/HomePage.jsx, src/Settings/Identity/Onboarding/Cards.jsx
depends upon https://github.com/near/near-discovery/pull/1019
=> sign-in now uses the new fastauth modal overlayed on top of the current page or the applications page

src/NearOrg/CookiePrompt.jsx
relates to https://github.com/near/near-discovery/pull/1027
=> only Required cookies were enabled for all users due to error in passing boolean values

src/Events/Index.jsx
There might be a case when there won't be any upcoming events so this PR introduces a couple of placeholders to inform users about that.
=> chore: add placeholders to events page

src/NearOrg/FoundersPage.jsx
Closes https://github.com/near/near-discovery/issues/1020
=> chore: style improvements of founders page

src/AI/Agent/AgentCreate.jsx, src/AI/Agent/AgentHeader.jsx
Improve validation function, support touch events in header.
=> fix: better validation for create or edit agents

src/Entities/Template/EntityCreate.jsx, src/Entities/Template/EntityList.jsx, src/Entities/Template/EntityPage.jsx
* EntityCreate supports creation of any entity type whose schema is passed in.
* EntityList supports passing in a custom loadItems function and tabular rendering functions.
=> feat: entity create

src/Blog/Feed.jsx, src/BlogPostPage.jsx
=> Restyle blog to adhere to figma design

replacements.dev.json, replacements.mainnet.json, replacements.testnet.json, src/Entities/Template/EntityCreate.jsx, src/Entities/Template/EntityList.jsx
Adds environment replacement for devhub.near components.
Removes unused REPL_QUERYAPI_FEED replacement.
=> chore: repl_devhub

src/Moderation/Moderator.jsx, src/Moderation/NeedsModeration.jsx
Moderator Tab state and default tabs work with sidebar.
=> Tab state with sidebar

src/Entities/Template/EntityCreate.jsx
logoUrl field was getting transformed, this moves towards determining the field type from the schema.
=> fix: force initial string values in form configurator

indexers/agents/agents.js, indexers/agents/agents.sql, src/AI/Agent/AgentCreate.jsx, src/AI/Nexus.jsx, src/Entities/QueryApi/Client.jsx, src/Entities/Template/EntityCreate.jsx, src/Entities/Template/EntityDetails.jsx, src/Entities/Template/EntityList.jsx, src/Entities/Template/EntitySummary.jsx, src/Entities/Template/GenericEntityConfig.jsx, src/Entities/Template/GenericSchema.jsx
Generic entity details components extracted from agent components
=> Entity details

src/NearOrg/Ecosystem/GetFundingPage.jsx
Closes https://github.com/near/near-discovery/issues/1076
=> chore: update marketing dao logo

src/PostPage.jsx, src/ProfileEditor.jsx, src/ProfilePage.jsx
A quick update to add a proper container for:
- ProfilePage
- ProfileEditor
- PostPage
=> Fix: Container for Profile and Post Pages

indexers/agents/agents.js, indexers/entities/entities.js, indexers/entities/entities.sql, src/Entities/Examples/ComponentSchema.jsx, src/Entities/Examples/ComponentsPage.jsx, src/Entities/Examples/FavoriteCarSchema.jsx, src/Entities/Examples/FavoriteCars.jsx, src/Entities/Examples/FavoritePlaces.jsx
Updated examples of various ways one can use the entity framework
=> Entity examples

indexers/entities/entities.js, src/Entities/Template/EntityDetails.jsx, src/Entities/Template/EntitySummary.jsx, src/Entities/Template/GenericEntityConfig.jsx
=> Entity delete

src/Gateway/Home.jsx
Closes https://github.com/near/near-discovery/issues/1091
=> chore: add hover effects on gatewat home page

src/NearOrg/Notifications/Notification.jsx, src/NearOrg/Notifications/utils.jsx
I noticed this issue with very long username, so this PR introduces changes to fix this
=> fix: add overflow to username on notifications

indexers/components/components.js, indexers/entities/entities.js, src/Entities/Examples/FavoriteCars.jsx, src/Entities/Examples/FavoritePlaces.jsx, src/Entities/QueryApi/Client.jsx, src/Entities/Template/EntityCreate.jsx, src/Entities/Template/EntityDetails.jsx, src/Entities/Template/EntitySummary.jsx, src/Entities/Template/GenericEntityConfig.jsx
* reduce user storage costs by only storing latest entity action
* fix typo in components indexer
* small updates to examples
* Fetch entity details from QueryApi
=> feat: write only latest entity change, misc

src/NearOrg/DataAvailabilityPage.jsx
Updates the copy on the DataAvailabilityPage.jsx file for increasing keyword density in order to improve the SEO ranking.
=> enhancement: Update data availability copy

src/NearOrg/DataAvailabilityPage.jsx
One last tweak to DA copy at the bottom
=> Data availability copy edit

src/AI/Agent/AgentCard.jsx, src/AI/Agent/AgentChat.jsx, src/AI/Agent/AgentDetails.jsx, src/AI/Agent/AgentSummary.jsx, src/ActivityFeeds/PostsFeedControls.jsx, src/ComponentDetailsPage.jsx, src/ComponentSummary.jsx, src/GatewayWrapper.jsx, src/Moderation/ModerationButton.jsx, src/Moderation/Moderator.jsx, src/Moderation/NeedsModeration.jsx, src/Moderation/ReasonDialog.jsx, src/ProfilePage.jsx, src/SocialIndexActionButton.jsx
Partially Implements: https://github.com/near/near-discovery/issues/1056
This PR should be merged before the 2nd PR to make testing easier. The changes in this PR are fully backwards compatible without the 2nd PR being merged/deployed yet.
More details are provided on the 2nd PR: https://github.com/near/near-discovery/pull/1103
=> Pinned Apps (1 of 2)

src/NearOrg/DataAvailabilityPage.jsx, src/NearOrg/HomePage.jsx
define B.O.S at it's first reference and update Fast Auth link.
=> Home update

src/Gateway/Home.jsx, src/NearOrg/DataAvailabilityPage.jsx
As per our discussion with @charleslavon this PR introduces a better hover effect for trending apps.
https://github.com/near/near-discovery-components/assets/34593263/7ef01602-d63e-4215-b325-9d30f81f3401
I haven't touched the `src/NearOrg/DataAvailabilityPage.jsx` file, it was affected by `prettier`.
=> chore: add more obvious hover effect to the trending app item

src/BlogPostPage.jsx
Companion PR with https://github.com/near/near-discovery/pull/1111 to close [1094(https://github.com/near/near-discovery/issues/1094)
=> feat: add meta tag feature to blogpost pages

src/NearOrg/Notifications/NotificationButton.jsx, src/NearOrg/Notifications/NotificationsMiddleware.jsx
=> exit early from the render function until the fetchGraphQL module loads

indexers/entities/entities.js, indexers/entities/entities_tests.js, indexers/entities/test_block.js
An empty key in the data `"": ''` was causing the error.
Note: Working toward tests for the indexers.
Note: Tried to make this a clean training case. Issue->PR with test.
Note: code has been deployed to production through QueryApi
=> fix: entities indexer handles empty namespace key

src/Entities/Template/EntityCreate.jsx
Flattens `attributes` column (which is a postgres jsonb column) for use in the edit dialog
=> Populate edit view with attributes

src/ComponentCard.jsx, src/ComponentSummary.jsx, src/NearOrg/CookiePrompt.jsx, src/News/NearweekSidebarFeed.jsx
This PR doesn't contain any breaking change or so. It just removes some of very simple errors and makes our local development cleaner. Originally, this was about to fix `svg` properties but then I realized we can simply remove it and use ph-icons
=> chore: get rid of some simple errors

src/NearOrg/BlockchainPage.jsx, src/NearOrg/HomePage.jsx
Ensure the Create Account CTAs trigger the auth modals
=> Ensure the Create Account CTAs trigger the auth modals

src/Entities/Template/EntityDetails.jsx, src/Entities/Template/EntitySummary.jsx, src/Entities/Template/GenericEntityConfig.jsx
Corrected star count variable
Show additional detail tabs when additionalTabs prop is present
Spread entity.attributes for use in edit tab
=> fix: star count, additional tabs on detail

src/Entities/QueryApi/Ipfs.jsx, src/Entities/Template/EntityCreate.jsx, src/Entities/Template/EntityDetails.jsx, src/Entities/Template/Forms/FormBuilder.jsx, src/Entities/Template/GenericEntityConfig.jsx, src/Entities/Template/GenericSchema.jsx
* Field type of "file" results in a file upload input
* Image files can be a `http` url or an uploaded file.
=> Entity file upload

src/NearOrg/DataAvailabilityPage.jsx, src/Posts/Post.jsx, src/Posts/RepostButton.jsx
All of the reposts work is in progress, this commit is to close out the blog post ui changes [issue](https://github.com/near/near-discovery/issues/993), however the work is inside of the "Reposts" button and the repost work itself is incomplete.
Closes: https://github.com/near/near-discovery/issues/993
=> feat: add repost button that handles post to blog

src/DIG/Input.jsx, src/DIG/Tabs.jsx, src/Entities/Template/EntityDetails.jsx, src/Entities/Template/EntityList.jsx, src/Entities/Template/GenericEntityConfig.jsx, src/Gateway/Home.jsx, src/Select.jsx
Related To: https://github.com/near/ai-platform/issues/11
I needed to update some of our core components to improve the mobile views for AI Nexus.
Part 2: https://github.com/near/ai-platform/pull/57
=> AI Mobile Part (1 of 2)

src/QueryApi/DataPlatformIndexerStatuses.jsx
Merge after https://github.com/near/near-discovery-components/pull/785 is deployed to main
=> chore: cleanup old folder

src/Entities/QueryApi/Ipfs.jsx, src/Entities/Template/EntityDetails.jsx, src/Entities/Template/EntityList.jsx, src/Entities/Template/Forms/FormBuilder.jsx, src/Entities/Template/GenericEntityConfig.jsx
Display only one of the image input methods according to current value and what the user chooses.
* Also restore grid columns
=> feat: toggle image input between url and file upload

src/NearOrg/FoundersPage.jsx
Closes: https://github.com/near/near-discovery/issues/1149
=> Add builder perks content

src/Gateway/Home.jsx
=> chore: update the homepage to feature fullstack development resources

src/Entities/Template/EntityDetails.jsx, src/Entities/Template/EntitySummary.jsx, src/Entities/Template/GenericEntityConfig.jsx
* clean up copy/share urls
* summary component accepts action param (eliminates custom summary components)
*  ipfs image support in EntitySummary
=> fix: clean up 

src/BlogPostPage.jsx
Closes: https://github.com/near/near-discovery-components/issues/793
Part 2: https://github.com/near/near-discovery/pull/1173
=> Conditionally render NearOrg.Footer on BlogPostPage (1 of 2)

src/Posts/Menu.jsx
Remove promote from the action menu
=> chore: remove promote from action menu

src/Settings/Identity/Index.jsx, src/Settings/Identity/Onboarding/Cards.jsx
Part 2: https://github.com/near/near-discovery/pull/1187
=> chore: update idos create account url (1 of 2)

src/Search/TypeAheadDropdown.jsx
This PR introduces changes to `TypeAheadDropdown` component for `All` tab only.
=> chore: improve `All` tab for search results

src/Search/TypeAheadDropdown.jsx
* chore: improve `All` tab for search results
* chore: change data structure
* chore: cleanup
* chore: remove unused props
=> chore: improve `All` tab for search results (#823)

src/Gateway/ContactUsPage.jsx, src/Gateway/Home.jsx, src/Navigation/NameDropdown.jsx, src/Navigation/Search.jsx
We added minor changes to some widgets, and added a new "menu" widget that is activated using the user name instead of its profile picture
=> chore: deploy testnet widgets on mainnet

src/Gateway/ContactUsPage.jsx
closes [#1210](https://github.com/near/near-discovery/issues/1210)
=> chore: re-add the Resolve an Issue card
