near/near-discovery-components

- src/ComponentDetailsPage.jsx
- src/NestedDiscussions.jsx
- src/NestedDiscussions/Compose.jsx
- src/NestedDiscussions/Feed.jsx
- src/NestedDiscussions/Preview.jsx
- src/NestedDiscussions/Preview/CommentButton.jsx
- src/NestedDiscussions/Preview/LikeButton.jsx
Before this PR notifications of discussions would show only one comment (the one referred by the notification). This is a problem in discussions, since the people need context to discuss.
Now, the notifications send the user back to the discussion, highlighting which comment is the notification referring to.
Changing this behaviour for better has also actually helped to simplify the discussions component a lot.
> Better discussions

- src/ComponentDetailsPage.jsx
Custom notifications for discussion lead to a broken link, since the `src` parameter is missing.
> fixed missing src param

- src/ComponentDetailsPage.jsx
- src/ComponentHistory.jsx
- src/Posts.jsx
For my Friday project, I decided to fork the current widget we're using to display commit history to improve the design:
I've switched out the component details page to use this new version. Feel free to pull down and test locally with `bos-loader`.
> Forking History Component

- src/Search/TypeAheadDropdown.jsx
forgot I made `const result = []` an array, so adjusted the code for it to be joined string at the end
> fix: encodeURIComponent result array

- src/AccountProfileInline.jsx
- src/AccountProfileOverlay.jsx
Fixes text overflow issues with long account ID's: https://near.org/near/widget/PostPage?accountId=youngfreshcreative.near&blockHeight=95064892
> Account Text Overflow

- src/ProfileEditor.jsx
this is actually a bug in production as well. On near.org, the profile page is `near/widget/ProfilePage` and from there you can open the editor which is `near/widget/ProfileEditor` but the preview displayed there does not show the correct ProfilePage component, it still references `mob.near/widget/ProfilePage`
> use proper preview on ProfileEditor

- src/DIG/Tooltip.jsx
- src/DIG/Tooltip.metadata.json
Example
```jsx
return (
<Widget
src="near/widget/DIG.Tooltip"
props={{
content: "This is my tooltip content.",
trigger: (
<Widget src="near/widget/DIG.Button" props={{ label: "Hover Me" }} />
),
}}
/>
);
```
> DIG.Tooltip

- replacements.dev.json
- replacements.mainnet.json
- replacements.testnet.json
- src/ActivityPage.jsx
Support for QueryAPI powered feed that has a fallback to `near/widget/posts` widget
> DPLT-1067 feat: support for queryapi feed widget

- src/DIG/Tabs.jsx
With this fix there will be a preview with default values of tabs.
Relates to: https://pagodaplatform.atlassian.net/browse/DEC-1347
> Provide default items of `DIG.Tabs` for preview

- src/IndexFeed.jsx
This either fixes the React Minify error completely, or is a step towards that direction.
once this is deployed into `develop` we can test the discussions component @ https://test.near.org/discom.testnet/widget/ComponentDetailsPage?src=discom.testnet/widget/ActivityPage&tab=discussion
> fix: Math.max with an undefined argument resulted in NaN where an integer was expected.

- src/ActivityPage.jsx
- src/v1/Feed.jsx
- src/v1/Posts.jsx
- src/v1/Posts/Feed.jsx
- src/v1/Posts/Post.jsx
We have recently adopted QueryAPI to power the near.org feed. QueryAPI is still in beta and there is a chance in the future that there is a time out or lag or issues relating to the service which could potentially cause downtime. 
To mitigate this, this PR implements a fallback mechanism by checking which of the two API's has the latest post: `QueryAPI` VS `SocialAPI`. It defaults to QueryAPI, but if the lag between the blockheight is more than 2, then it fallsback to the old widgets.
> feat: implement fallback to old feed that supports SocialAPI

- src/NestedDiscussions/Compose.jsx
- src/Posts/Compose.jsx
- src/Posts/Edit.jsx
After moving to QueryApi to upload posts feed we lost an ability preview posts when creating one. And the problem was simple: `Posts.Post` component returns "loading..." text if there is no such post. Which means we should use `v1.Posts.Post` for each component where we want to preview post because we don't need to make some call to preview post
> Fix post preview

- src/AccountProfileOverlay.jsx
- src/Comments/Comment.jsx
- src/FlagButton.jsx
- src/NestedDiscussions/Preview.jsx
- src/Posts/Post.jsx
- src/v1/Posts/Post.jsx
Basically you can flag you own post, comment, discussion and account. Once you do that and open your profile page you'll see this error:
Of course we have to handle it on the IndexFeed component but let's add a `disable` prop at first.
> Add `disabled` to FlagButton

- src/ProfilePage.jsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1444
There was a bug on profile page that user can't see any posts (maybe it was on my page only but I don't think so)
I thought it's the problem of `IndexFeed` component and started to look for problem there in fact that it was working well earlier. I checked [this](https://near.org/near/widget/ComponentDetailsPage?src=mob.near/widget/IndexFeed) version of `IndexFeed` created and maintained by Eugene and the problem has gone.
Long story short: after we start using QueryAPI queries, this functional got broken too, and I fixed that by changing the src of component
`${REPL_ACCOUNT}/widget/Posts.Feed` -> `${REPL_ACCOUNT}/widget/v1.Posts.Feed`
but the thing is - I was wrong because I should change that to …
> Fix rendering posts on profile page

- src/DIG/OverviewPage.jsx
- src/DIG/OverviewPage.metadata.json
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1443
Implements a DIG Overview page that dynamically fetches and lists all DIG components published by `REPL_ACCOUNT` in the current environment. This is just an MVP design until we can come up with something better down the road.
NOTE: Currently, we have changes in `develop` that haven't been published to `main` yet. This means if you're looking at this page in the `mainnet` environment locally, some of the component previews will show errors since the latest component description changes haven't been published yet. These will be resolved once we sync everything.
> DIG Overview Page MVP

- src/NearOrg/Notifications/NotificationAlert.jsx
After #357 there are more items added to `DIG.Dialog`. See the whole list of props described [here](https://test.near.org/discom.testnet/widget/ComponentDetailsPage?src=discom.testnet/widget/DIG.Dialog).
But I want to highlight a few of them here:
- `actionStyles` - defined styles for buttons row. From now you can only pass css styles directly;
- `content` - pass your own content and it will be right after `title` and `description`. You can ignore passing `title` and `description` and provide your own elements with styling;
- `actionButtons` - allows to pass your own buttons or whatever you want (similar to `content`). This prop overrides action button properties given before so you have to define event handlers for each custom button by your own. Here is the whole list of ignored …
> Fix styling prop of `NotificationAlert`

- src/NearOrg/Notifications/HomeScreenAlert.jsx
Closes [#604](https://github.com/near/near-discovery/issues/604)
> Prepare iOS Home Page prompt

- src/NearOrg/Notifications/NotificationAlert.jsx
This PR introduces different placement of NotificationAlert for iOS devices.
Relates to [#652](https://github.com/near/near-discovery/pull/652)
> Add different styles for NotificationAlert based on device

- src/Moderation/ModerateAccounts.jsx
- src/Moderation/ModerateComments.jsx
- src/Moderation/ModeratePosts.jsx
- src/Moderation/Moderator.jsx
* Tabbed moderation page
* Moderate a post feature
* Moderate a comment feature
* Un-moderate actions write a delete operation to the index. This is applied in the UI.
* Moderation actions are written in SocialDB index format
> Moderate account
> ```
> {
>   "bosmod.near": {
>     "index": {
>       "moderate": "[{\"key\":\"bosmod.near\",\"value\":{\"path\":\"badaccount.near\",\"label\":\"moderate\"}}]"
>     }
>   }
> }
> ```
> 
> Moderate post
> ```
> {
>   "bosmod.near": {
>     "index": {
>       "moderate": "{\"key\":\"bosmod.near/post/main\",\"value\":{\"path\":\"badaccount.near/post/main\",\"blockHeight\":\"95781851\",\"label\":\"moderate\"}}"
>     }
>   }
> }
> ```
> 
> Moderate comment
> ```
> {
>   "bosmod.near": {
>     "index": {
>       "moderate": …
```
> #517 Moderate a post and first pass of new moderation page.

- src/ProfilePage.jsx
The ProfilePage now looks to see if a user has a custom profile. When a user forks ProfilePage to create their custom profile, to start with it will have the custom profile loading code. Users will likely not notice this, causing an infinite loop.
This sets a flag to prevent that loop.
> Prevent custom profiles from trying to load themselves.

- src/Posts.jsx
- src/Posts/Menu.jsx
- src/Posts/Post.jsx
This is first portion of the new reporting flow [design](https://www.figma.com/proto/bD7wRz3SLLh0N2EwTFjFEQ/Reporting?type=design&node-id=123-1204&t=Nrz0fJqa8Mti60YN-0&scaling=min-zoom&page-id=1%3A2&starting-point-node-id=114%3A1535)
-  Post menu has hide and report post and account options. 
- Hide Toast without re-showing post.
- Hides and reports are in new moderation data structure.
PR is ready for review it just needs to be merged with other moderation PRs.
> 393 implement reporting content flow

- src/NearOrg/Notifications/Notification.jsx
@shelegdmitriy or @calebjacob my fix is probably the sloppiest approach. Would you suggest an alternative?
before: 
with this PR (ignore the super wide display):
> chore: fix alignment issue

- .github/workflows/deploy-prod-testnet.yml
In response to [this comment](https://github.com/near/near-discovery-components/pull/107#issuecomment-1764474256)
> fix: sets prod-testnet-deploy to track main branch

- indexers/README.md
- indexers/moderation/moderation.js
- indexers/moderation/moderation.sql
- indexers/social_feed/social_feed.js
- indexers/social_feed/social_feed.sql
- indexers/verifications/verifications.js
- indexers/verifications/verifications.sql
- src/ActivityPage.jsx
- src/Moderation/ModerateAccounts.jsx
- src/Moderation/ModerateComments.jsx
- src/Moderation/ModeratePosts.jsx
- src/Posts.jsx
- src/Posts/Menu.jsx
- src/Posts/Post.jsx
Fixed version of Filter ActivityFeed based on new moderation format.
This is the same as what was merged yesterday with the addition of null checks on the Social.getr method when fetching selfModeration data and the same for selfFlagged data. 
Also switched the fallback/lag check in ActivityPage to use the dataplatform_near_moderated_posts table for consistency.
> 375 filter activityfeed based on new moderation format

- src/ComponentCard.jsx
Issue was found by @TiffanyGYJ:
With my latest performance changes, we weren't properly parsing `props.metadata.tags` when `props.metadata` is passed in to avoid the extra `Social.get()` call.
> Fix Featured/Latest Component Tags

- src/Moderation/ModerateAccounts.jsx
- src/Moderation/ModerateComments.jsx
- src/Moderation/ModeratePosts.jsx
- src/Moderation/Moderator.jsx
- src/Moderation/NeedsModeration.jsx
- src/Moderation/Sidebar.jsx
- src/Moderation/TogglingSetButton.jsx
Note, if you test this locally, it only works against `mainnet` due to the dependency on QueryApi. To fully test end to end with a user other than `bosmod.near` reach out to Gabe.
Moderator
* Moderator interface has sidebar for Overview, Needs Moderation, Previously Moderated.
* Previously Moderated interface allows unmoderation of content and manual moderation.
* Needs Moderation interface allows moderators to work with feed of reported, not yet moderated content.
Needs Moderation
* Lists Reported Accounts, Posts, Comments in one feed, grouped by each reported item.
* Content is hidden until expanded. Meta info in header and header tooltips.
* Posts and Comments can be individually blocked or whole account can be moderated.
* Expanded content shows account, post, or comment
* Moderated …
> Needs Moderation interface shows reported accounts posts comments

- src/NearOrg/Notifications/Notification.jsx
Fixes https://github.com/near/near-discovery/issues/584.
The issue has been raised due to the problem of the whitespace within the notification. Instead of directing to the content, it redirects to the user's profile. However the whitespace in notification it is not clickable and the reason the issue is happening it's because the width of profile picture in notification it's very long.
Take a look a the picture below:
In the current pull request, I have made some CSS changes to address this issue.
After further investigations we decided not to include clickable whitespace functionality because of the different types of notifications.
> Fixed CSS in notification profile picture

- src/ActivityFeeds/DetermineActivityFeed.jsx
- src/ActivityFeeds/PostsFeedControls.jsx
- src/ProfilePage.jsx
Main features
* By using the main Activity feed, standard moderation and self-moderation is applied to the content.
* Add account filter to Activity feed 
* Use Activity Feed on Profile Page with account filter
* Add Mutual Activity feed for use on profile page instead of Following Feed
Small adjustments
* Only show feed selector if there is more than one.
* Show sort selector for all feeds
* property determines whether to show Compose Post area.
This is a screenshot of the Overview portion of a user's profile (when viewed by a different user).
> Use ActivityFeed on ProfilePage

- src/GatewayWrapper.jsx
- src/NearOrg/PrivacyPage.jsx
- src/NearOrg/TermsPage.jsx
- src/TosCheck.jsx
- src/TosContent.jsx
Relates to [#525](https://github.com/near/near-discovery/issues/525), [#526](https://github.com/near/near-discovery/issues/526)
Closes [#727](https://github.com/near/near-discovery/issues/727)
This PR introduces new terms and privacy docs which stores in new infura account. All the credentials could be found in 1Password.
Also this PR includes:
- style changes for ToS modal to be aligned with other gateway components;
- new terms and privacy pages;
> Update terms and privacy

- src/PeoplePage.jsx
Routing for link /people in Header > Ecosystem > People should redirect to PeoplePage?tab=trending
> feat() Routing /people to PeoplePage trending tab, if no props are set

- src/ActivityPageFeed.jsx
- src/Posts.jsx
Notices that ActivityPageFeed and Posts have moved and that the old component location is deprecated.
src/Feed.jsx and src/Feed/Post.jsx (also removed in [4e3f92](https://github.com/near/near-discovery-components/commit/4e3f9278badf06a6c753dc3d5e9965a2f08e2f8d)) looked out of date enough that it's not worth adding deprecation notices for them.
> Activity feed moved deprecation notices

- src/Posts/Menu.jsx
- src/ProfilePage/Sidebar.jsx
The hide/report menu can be the entry point for all self-moderation actions. This updates it to show only account actions if no blockheight is passed. On the ProfilePage flag account is replaced with the menu.
> Replace flag account with hide/report menu with only account options

- src/ActivityFeeds/DetermineActivityFeed.jsx
Determine fallback was looking at moderated_posts to determine whether QueryApi is up to date with Social.index. If the latest post is moderated then fallback could be triggered even though it is up to date.
> Use posts table to determine whether QueryApi matches Social.index.

- indexers/moderation/moderation.js
- indexers/moderation/moderation.sql
- src/Moderation/Moderator.jsx
- src/Moderation/NeedsModeration.jsx
- src/Moderation/TogglingSetButton.jsx
Fix: On overview page display logged in user instead of the moderator account.
Fix: Await graphql call in Moderation indexer to avoid indexer failure if there is an error.
Fix: Moderating an account from the Needs Moderation page writes to an incorrect Social.index key due to undefined path being appended.
Fix: Remove  receipt_id column in the needs_moderation as it is causing duplicates.
Fix: Correct subquery join for reporter list in unmoderated_reports to pull in reporters for reported accounts.
Feature: Disable Moderation buttons on Needs Moderation interface when not logged in as a moderator.
> Fix several small Moderator interface bugs

- src/Settings/Identity/Verifications/Card.jsx
- src/Settings/Index.jsx
- src/Settings/Sidebar.jsx
This PR introduces a mobile view for Settings page. This is how it looks like:
I have hidden the tabs in the Sidebar because so far we only have 1 tab. If we add more tabs they will be shown automatically.
> Add mobile view to the Settings page

- src/AppLibrary/Nearcon/IndexPage.jsx
This change was accidentally checked in and thus is counting the leaderboard wrong.
> fix stats for ncon app quest

- src/Settings/Identity/Index.jsx
- src/Settings/Identity/Verifications/Index.jsx
For some reason the modal won't fires up after clicking on `Add Credential` button. There is no error or so and I can reproduce this issue very rarely. That's why I decided to remove modal and user will be redirected to fractal after clicking on  `Add Credential` button.
> Fix `Add Credentials` button on settings page

- src/NearOrg/Footer.jsx
We can safely merge this into `develop` now. We'll open another PR to sync `main` tomorrow (on the 8th).
> Show data availability link in footer

- indexers/social_feed/social_feed.js
The introduction of context.db methods allows for simpler databasse interaction. I've replaced the graphql calls with db calls to demonstrate the gains in simplicity. In addition, the blocks 100505912 and 105013604 both cause the indexer to crash. I've added more try catches to ensure the indexer skips those blocks rather than crashes.
> Replace Graphql Calls with Context Db Calls

- .github/release.yml
Adding bot as an author whose changes to ignore. I think this will skip creating release notes records for the auto-generated develop-> merge PRs
> fix release.yml formatting, with unicode for the emojis

- src/Search/Facets.jsx
- src/Search/TypeAheadDropdown.jsx
Closes: https://github.com/near/near-discovery/issues/782
- Convert tabs from `<a>` to `<button>` tags
- Fix style issues
> Fix Search Typeahead Tabs

- src/Search/TypeAheadDropdown.jsx
Fixes https://github.com/near/near-discovery/issues/807 .
This PR is related with: https://github.com/near/near-discovery/pull/821
> Added handleCloseSearchMenu to close search UI 

- src/ComponentDetailsPage.jsx
- src/ComponentHistory.jsx
Closes: https://github.com/near/near-discovery/issues/814
After talking with @charleslavon, we decided to implement the following on the component details page:
- Shrink the sidebar width a bit to give the code more room
- The `Code` tab now only renders the current code
- The `Preview` tab now only renders the current preview
- The `History` tab shows the commit history and diffs
> Code and History Tabs

- src/ComponentSummary.jsx
When we merged changes to remove the NEAR Con upvote button, we also lost our new Star button. This adds it back.
> Add back star component button after accidentally being removed

- src/NearOrg/Notifications/Notification.jsx
This PR introduces a fix for DevHub post links on notifications page.
Closes [#830](https://github.com/near/near-discovery/issues/830)
> fix: Fix link to DevHub posts on notifications page

- src/ExploreWidgets.jsx
- src/News/NearweekSidebarFeed.jsx
Forking `nearweekapp.near/widget/NEARWEEKNews` and implementing fix for timestamp fetch. I was able to keep the timestamp by simply using the same endpoint that `TimeAgo` uses:
```js
const timeResponse = fetch(`https://api.near.social/time?blockHeight=${post.blockHeight}`);
```
This removes the `Near.block()` call that was causing the request to the archival node.
> Fork NEARWEEKNews and fix timestamp

- src/News/NearweekSidebarFeed.jsx
This pull request is submitted as a suggestion to address the issue:
https://github.com/near/near-discovery-components/issues/459
Limited the number of posts fetched from the `Social.index`
Since we display only 5 posts on the sidebar, fetching more would be unnecessary.
So in this case we limited the number of `indexed posts` by the `limit` value.
With this adjustment, we've successfully reduced the number of HTTP requests.
> refactor: Limit number of indexed Post in nearWeekNews

- src/DIG/OverviewPage.jsx
Fixes: https://github.com/near/near-discovery/issues/872
Turns out we were hitting a gas limit due to our previous logic fetching all components on our official account (including their code). Now we only fetch the full details of our `DIG` components.
> Fix DIG.OverviewPage Fetch

- src/ActivityPage.jsx
Added `onClick` handler directly to the `TabsButton` component to set the selected tab with `setSelectedTab`.
Closes https://github.com/near/near-discovery/issues/693
> feat: Add click directly on TabsButton

- src/Comments/Comment.jsx
- src/Posts/Post.jsx
This PR addresses the flag button ( image below ) and removes it from both posts and comments, as we have the `three dots menu` in the report option instead.
> fix: Remove Flag button from Posts and Comments

- src/DIG/DropdownMenu.jsx
This pull request addresses a UI concern related to the Post action dropdown showing after the newsletter section 
as documented in: [Issue: 448](https://github.com/near/near-discovery-components/issues/448)
Added z-index to Radix Popover Content since it has a fixed position.
Note: This change will result in also resolving the Profile Overlay Display issue [#879](https://github.com/near/near-discovery/issues/879)
> NEAR-448 FIX: Updated z-index for Radix Popover due to underlying UI issues

- src/ActivityFeeds/DetermineActivityFeed.jsx
- src/ActivityFeeds/PostsFeedControls.jsx
- src/ActivityPage.jsx
Every 5s, fetches latest posts and adds them to the `newUnseenPosts` list.
When new posts are present shows refresh control. Clicking that will add the unseen posts to the displayed list (preserving all loaded posts) and resets the `initialQueryTime` used by the update task.
Paging uses the `initialQueryTime` to keep the offset constant when paging.
Minor updates to sort selector and its text to get closer to the latest UI designs
> feat: update unseen posts every 5s 

- src/AccountProfileOverlay.jsx
- src/Posts/Post.jsx
Due to Radix Popover having set the z-index to auto, most of the content which have a higher z-index will result in the Profile Overlay showing before content.
This PR will close this issue: [Issue: 879](https://github.com/near/near-discovery/issues/879)
> NEAR-879 FIX: Updated z-index for profile overlay issue

- src/AccountProfile.jsx
- src/Recommender/Account/AccountProfileSidebar.jsx
This pull request addresses the issue ( https://github.com/near/near-discovery-components/issues/596 ) of unnecessary page reloads when clicking on a user profile.
The change involves replacing the usage of the `a` element with the `Link` in two different files ( AccountProfile and AccountProfileSidebar. )
> fix: Replaced a with Link to prevent unnecessary page reloads on profile

- src/ProfilePage.jsx
Fixes: https://github.com/near/near-discovery/issues/843
The issue here was with using `display: grid` with wrong media breakpoints. It was still rendering the desktop version of main section when it was too small. Since the breakpoint was set to `1024px` and the section was rendered on half of the screen it didn't have room to display correctly.
**Solution:**
Instead of using `display: grid` I used `display: flex` and set it to wrap automatically when there is no more room for the content to display correctly.
Regarding the fourth point in the issue ("'Most recent' dropdown looks buggy and 'Sort by' has incorrect font - bug"):
It looks like the layout is different now and there is no sorting feature anymore.
Before                            |  After …
> fix: fixed styling bugs in profile editor view

- src/ProfilePage.jsx
Closes: https://github.com/near/near-discovery-components/issues/590
We're still waiting for the backfill to finish on the indexer before we merge this, but everything is ready to go! Feel free to test out locally by visiting your profile page.
Account with contributions: http://localhost:3000/near/widget/ProfilePage?accountId=near
Account without any contributions: http://localhost:3000/near/widget/ProfilePage?accountId=joshford.near
> Adding contribution graph to profile page

- replacements.testnet.json
- src/Comments/Comment.jsx
- src/v1/LikeButton.jsx
Fixes: https://github.com/near/near-discovery/issues/668
There is already logic to handle notification sending when liking comment. 
The issue was with `notifyAccountId` being set to `undefined` in `src/Comments/Comment.jsx`. When checking whether to send notification `notifyAccountId` needs to be truthy. Since it was set to `undefined` and never modified after that it would not send the notification.
I also added a check to prevent sending notifications to yourself when liking own comment.
> Enable sending notifications for interactions on comment

- src/Search/TypeAheadDropdown.jsx
This PR addresses the issue https://github.com/near/near-discovery/issues/912 for closing the search bar after clicking on the desired/suggested options.
- Added `handleCloseSearchMenu` to the `<Item>` to handle the closing of the search menu when a search result is clicked.
> fix: Added handleCloseSearchMenu to close the search bar

- src/NearOrg/Notifications/Notification.jsx
This PR addresses https://github.com/near/near-discovery/issues/908 with the issue of the long notification content UI ( picture below ).
- Added `word-break: break-word` to `Description` tag which fixed both cases in `notification` and `notification dropdown menu`.
> fix: Fixed notification long horizontal content 

- src/NearOrg/Notifications/utils.jsx
This pull request addresses the issue https://github.com/near/near-discovery-components/issues/626 for redirecting to the `Page not found` preview after clicking `view` on like type of notification.
- Added check for `isComment` to redirect to the `commentPost` page.
> fix: fixed view notification button preview for like type notification

- indexers/moderation/moderation.sql
- src/Moderation/NeedsModeration.jsx
Having multiple labels exposed an incorrect reporter count calculation on the Needs Moderation page. Added tooltip of sampled reporter list to confirm calculation.
> fix: correct reporter count & list on needs moderation page

- src/NearOrg/Notifications/Notification.jsx
- src/NearOrg/Notifications/utils.jsx
This pull request resolves the first point raised in issue https://github.com/near/near-discovery/issues/909 which fixes the content description not matching the action.
- Introduction of the `notificationValue` property for `getNotificationContent` function.
- Added `commentAuthorAccountId` to get the specific accountId
- Addition of `contentBlockHeight` to accurately capture the blockHeight for notifications of type `like`.
- Refactored `contentPath` and `contentDescription`.
> fix: fixed notification content description

- indexers/accounts/accounts.sql
Relates to [#855](https://github.com/near/near-discovery/issues/855)
> fix: add a `tags` field to accounts indexer schema

- src/NearOrg/DataAvailabilityPage.jsx
- src/NearOrg/HomePage.jsx
Closes #639 
Desktop:
Tablet:
Mobile:
> fix: trusted partners display should flex to mobile screens

- src/Comments/Compose.jsx
- src/Posts/Post.jsx
This draft PR aims to address the issue raised in https://github.com/near/near-discovery-components/issues/433 regarding updating the UI when a new comment is added to a post.
- Added `const newComment` when adding a comment.
- Added `addNewCommentFn` function to update the `state.comments` when a comment is pushed.
- Updated `Comments.Compose` widget.
The picture below shows what the last added comment will look like without reloading the page.
In the provided image, the latest added comment is displayed without the expected widgets for like, comment, and share. because of the `blockHeight` which is currently set to `now`.
> fix: Update UI when a new comment is added

- src/NearOrg/Notifications/NotificationButton.jsx
- src/NearOrg/Notifications/Notifications.jsx
- src/NearOrg/Notifications/NotificationsList.jsx
- src/NearOrg/Notifications/Preview.jsx
This PR introduces a couple of improvements:
1. Use [HoverCard](https://www.radix-ui.com/primitives/docs/components/hover-card) like it's already done for `AccountProfileOverlay` component;
2. Move notifications list preview to the separate component which gain us more control (like passing custom trigger component, etc);
3. Add `size` property to `NotificationsButton` component;
4. Delete unused variables;
5. Cleanup.
Which means it can be promoted into production as well.
> chore: refactor `NotificationButton`

- src/ActivityPage.jsx
- src/ComponentDetailsPage.jsx
- src/ComponentsPage.jsx
- src/Entities/Template/EntityList.jsx
- src/NearOrg/CookiePrompt.jsx
- src/NearOrg/Ecosystem/CommunityPage.jsx
- src/NearOrg/Ecosystem/GetFundingPage.jsx
- src/NearOrg/Ecosystem/OverviewPage.jsx
- src/NearOrg/Ecosystem/WorkAndEarnPage.jsx
- src/NearOrg/Notifications/Notifications.jsx
- src/NearOrg/Notifications/Settings.jsx
- src/NearOrg/PrivacyPage.jsx
- src/NearOrg/TermsPage.jsx
- src/NearOrg/UsePage.jsx
- src/PeoplePage.jsx
- src/Settings/Index.jsx
Closes: https://github.com/near/near-discovery-components/issues/710
- Swap out all usage of `container-xl` for `gateway-page-container`
- Refactored a few Styled Components props to use `$` prefix to get the ball rolling
This gateway PR is what introduces the new `gateway-page-container` class: https://github.com/near/near-discovery/pull/1069 - we'll want to try and merge/deploy both of these PR's at the same time for production. Otherwise, some of our pages will render without being properly centered.
> Container Refactor

- src/NearOrg/HomePage.jsx
- src/NearOrg/LatestEvents.jsx
Closes: https://github.com/near/near-discovery/issues/1060
Use `fetchEventsList()` passed in from gateway to fetch dynamic events data for home page.
This should be merged after this first PR: https://github.com/near/near-discovery/pull/1093
> Sync Home Page Events (2/2)

- indexers/agents/agents.js
- indexers/entities/entities.js
- indexers/entities/entities.sql
Entity indexer replaces the agent indexer.
Indexes everything in `social.near` below the `entities` key in each account space.
Indexes star actions on entities.
> Entity indexer

- indexers/agents/agents.js
- indexers/entities/entities.js
- indexers/entities/entities.sql
- src/Entities/Examples/ComponentSchema.jsx
- src/Entities/Examples/ComponentsPage.jsx
- src/Entities/Examples/FavoriteCarSchema.jsx
- src/Entities/Examples/FavoriteCars.jsx
- src/Entities/Examples/FavoritePlaces.jsx
- src/Entities/Template/EntityCreate.jsx
- src/Entities/Template/EntityDetails.jsx
- src/Entities/Template/EntitySummary.jsx
- src/Entities/Template/GenericEntityConfig.jsx
All entity framework data is now stored in the `social.near` contract under the `entities` key.
The next level below that is a namespace. Entities that don't specify a namespace will go under `default`. Next is the entity type then the entities themselves. So a  myCar `vehicle` entity in the `examples` namespace would be
```
<account_id>: { entities: { examples: { vehicle: { myCar: {...cardata}  } } } }
```
Staring an entity will use a `path` matching the same format.
> feat: entity namespaces and stars

- src/NearOrg/Notifications/Notification.jsx
- src/NearOrg/Notifications/NotificationsMiddleware.jsx
- src/NearOrg/Notifications/utils.jsx
This PR introduces an extra check for notification `value` param which needed to show notification properly. 
Well, we query for the notification data using queryApi. This means some params could be missed because of some new notification type or because the data itself has been created long time ago and indexer didn't collected them. That's why some notifications could be hidden for user or some parts of notification might not exist (as notification preview for example or entire `custom` notification).
Each notification type has required amount of params which needed to create a human readable message. So, I've added a method to check whatever a notification value (from QueryAPI) contain all the needed params. This check method depends on type of notification (this param comes from …
> fix: broken devhub notifications

- src/NearOrg/Notifications/NotificationButton.jsx
- src/NearOrg/Notifications/NotificationsList.jsx
This PR introduces fix for new notifications count. Also, I've added a query to fetch for new notifications from queryApi and not from chain. Fallback logic also included
> fix: notification counter

- src/Gateway/ContactUsPage.jsx
Partially implements: https://github.com/near/near-discovery/issues/1064
Implements new Contact Us page for the gateway. We should merge this before the 2nd PR.
Part 2: https://github.com/near/near-discovery/pull/1115
> Contact Us Page (1 of 2)

- src/Entities/Template/EntityList.jsx
- src/Entities/Template/Forms/TagCloud.jsx
- src/Entities/Template/GenericEntityConfig.jsx
- src/Moderation/Sidebar.jsx
* Used by the AI Nexus, this allows tag filters to be passed from an arbitrary component.
* Sidebar can have additional content passed
* TagCloud displays tags and accepts an onSelect handler
> feat: support global tag filtering for entities

- src/ActivityFeeds/DetermineActivityFeed.jsx
- src/ActivityFeeds/PostsFeedControls.jsx
- src/NearOrg/DataAvailabilityPage.jsx
- src/v1/Feed.jsx
- src/v1/Posts.jsx
- src/v1/Posts/Feed.jsx
This PR introduces a couple of cleanups of Post related components. As a part of this cleanup, I removed defining of `fetchGraphQL` method in order to use `VM.require()` for exact the same method:
```
const { fetchGraphQL } = VM.require("${REPL_ACCOUNT}/widget/Entities.QueryApi.Client");
```
> chore: cleanup of Post related components

- src/Gateway/Home.jsx
Related to this comment https://github.com/near/near-discovery-components/pull/797#discussion_r1589425136
> chore: use `gap` as it was before

- src/Blog/Feed.jsx
- src/BlogPostPage.jsx
Companion to [#1175](https://github.com/near/near-discovery/pull/1175) allowing for a gateway to set a custom url for their bosblog page implementation. Original request can be found [here](https://github.com/orgs/near/projects/92/views/6?pane=issue&itemId=61052380)
Also fixes [Bug](https://github.com/orgs/near/projects/92/views/6?pane=issue&itemId=61053805) where the "back to all posts" button url was undefined resulting in a broken link.
> fix: create blogComponentUrl as props to passed to the blog widget

- src/Search/ComponentCard.jsx
- src/Search/FullPage/ComponentCard.jsx
- src/Search/IndexPage.jsx
- src/Search/Insights.jsx
- src/Search/TypeAheadDropdown.jsx
This PR introduces changes for Algoria search. `replica_prod_near-social-feed` includes two indexes:
- `prod_near-social-feed` (production records);
- `test-near-catalog-index` (nearcatalog records);
[loom](https://www.loom.com/share/f59a0a634dd0491da471d8ce3ddc5089?sid=c9c50cde-b0d9-4fde-bf4c-05582bc7f29a) video
Closes https://github.com/near/docs/issues/1941
> feat: add nearcatalog records to improve search ux

- src/Navigation/Search.jsx
This PR addresses an issue where the search bar frequently loses focus. This problem was causing frustration for users who needed to repeatedly click on the input bar to continue typing and see auto-suggestions.
Check out this [message](https://pagodaplatform.slack.com/archives/C0559BC3WBZ/p1717521230244739) for additional context.
> fix: search input focus issue

- src/Gateway/Home.jsx
The [homepage](https://dev.near.org) is currently failing to load the trending apps from nearcatalog. Apparently nearcatalog's API has changed and returns the apps within a `data` field when requesting the most used apps:
https://nearcatalog.xyz/wp-json/nearcatalog/v1/projects-by-category?cid=trending
> fix: Gateway Homepage

- src/Navigation/NameDropdown.jsx
- src/Navigation/ProfileDropdown.jsx
- src/Navigation/Search.jsx
- src/Search/ComponentCard.jsx
- src/Search/IndexPage.jsx
- src/Search/TypeAheadDropdown.jsx
As per discussion with @charleslavon we decided to proceed with this https://github.com/near/near-discovery/issues/1196 issue by this way:
1. Remove search categories such as "posts", "posts-and-comments", "people" and leave **only** components including nearcatalog and widgets (about widgets I'm not sure, because don't remember);
2. Bring the top navbar back along with search (this is the **part 2** on the near-discovery side);
Closes https://github.com/near/near-discovery/issues/1196
Feel free to leave any questions you have!
> chore: reduce amount of search categories (Part 1/2)

- src/Gateway/ContactUsPage.jsx
Closes: https://github.com/near/near-discovery/issues/1210
- Copy updates to contact us page
- Open Gleap widget instead of redirecting to Zendesk page
> Update Contact Us Page (Gleap)

- src/Gateway/Home.jsx
This link is invisible for regular users. This is an interesting story and the tl;dr; is that I need to use playwright on dev.near.org to automate using the sandbox to repeatedly submit transactions to be able to efficiently burn through the[ trial-account](https://docs.keypom.xyz/docs/next/TrialAccounts/introduction) floor of 10 Near that I set on couple keypom accounts.
> chore: adds an invisible link to be used by playwright automation

- src/Gateway/Home.jsx
Reverts near/near-discovery-components#845
I think I can accomplish this directly via playwright code ```await page.setContent(`<style>
a {
zoom: 100%
}
</style>
<a href="/sandbox/>
`);
> Revert "chore: adds an invisible link to be used by playwright automation"

- src/NearOrg/Ecosystem/GetFundingPage.jsx
- src/NearOrg/FoundersPage.jsx
This PR revises outdated links on the NEAR FounderHub landing page to ensure all hyperlinks direct users to the correct and up-to-date information.
- Updated multiple outdated links on the NEAR FounderHub landing page to their current and correct destinations.
The previous links were outdated and could potentially mislead or confuse users. Updating these links is essential for providing accurate and useful information.
> chore: revised outdated links on NEAR FounderHub landing page

- src/Gateway/Home.jsx
The nearcatalog.xyz redesign moved their "trending apps" endpoint to a new URL.
> Fix: update nearcatalog.xyz url
